version: '3.6'
services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      MYSQL_USER: kleinekadee_user
      MYSQL_PASSWORD: kleinekadee_pass
      MYSQL_DATABASE: kleinekadee
      MYSQL_ROOT_PASSWORD: kleinekadeesudo
  wordpress:
    image: wordpress:latest
    ports:
    - "8585:80"
    depends_on:
    - "mysql"
    restart: always
    volumes:
    - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: kleinekadee_user
      WORDPRESS_DB_PASSWORD: kleinekadee_pass
      WORDPRESS_DB_NAME: kleinekadee
  wordpress-cli:
    depends_on:
    - mysql
    - wordpress
    image: wordpress:cli
    # vstm: This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    # vstm: The sleep 10 is required so that the command is run after
    # mysql is initialized. Depending on your machine this might take
    # longer or it can go faster.
    command: >
      /bin/sh -c '
      sleep 30;
      wp core install --path="/var/www/html" --url="http://localhost:8585" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=secret --admin_email=foo@bar.com;
      sleep 10;
      wp core update;
      sleep 10;
      wp plugin install woocommerce;
      sleep 10;
      wp plugin activate woocommerce;
      '
    # vstm: add shared volume
    volumes:
      - wp_data:/var/www/html
volumes:
  db_data:
  wp_data: